version: '3.9'
services:
  app1:
    build:
      context: .
    container_name: app1_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py

  app2:
    build:
      context: .
    container_name: app2_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python app2.py